name: Validate starter notebooks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-starters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install nbformat
      - name: Ensure starter notebooks are in sync
        run: python tools/generate_starters.py --check
