name: Validate starter notebooks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  sync-starters:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      starters_changed: ${{ steps.regen.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbconvert nbclient ipykernel pandas matplotlib seaborn plotly kaleido
      - name: Run solution notebooks
        run: |
          python - <<'PY'
          import nbformat
          from nbclient import NotebookClient
          from pathlib import Path

          notebooks = sorted(Path("days").glob("day*/solution/*.ipynb"))
          if not notebooks:
              raise SystemExit("No solution notebooks found")

          for nb_path in notebooks:
              print(f"Executing {nb_path}")
              nb = nbformat.read(nb_path.open(), as_version=4)
              client = NotebookClient(nb, timeout=600, kernel_name="python3")
              client.execute(cwd=str(Path.cwd()))
          PY
      - name: Regenerate starter notebooks
        id: regen
        run: |
          python tools/generate_starters.py
          if git status --porcelain | grep .; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit starter notebooks
        if: github.event_name == 'push' && steps.regen.outputs.changes == 'true'
        env:
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout "$TARGET_BRANCH"
          git add days plots
          git commit -m "chore: regenerate starter notebooks"
          git push origin HEAD

  execute-notebooks:
    runs-on: ubuntu-latest
    needs: sync-starters
    if: needs.sync-starters.outputs.starters_changed == 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install notebook runtime
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert nbclient ipykernel pandas matplotlib seaborn plotly kaleido
      - name: Run solution notebooks
        run: |
          python - <<'PY'
          import nbformat
          from nbclient import NotebookClient
          from pathlib import Path

          notebooks = sorted(Path("days").glob("day*/solution/*.ipynb"))
          if not notebooks:
              raise SystemExit("No solution notebooks found")

          for nb_path in notebooks:
              print(f"Executing {nb_path}")
              nb = nbformat.read(nb_path.open(), as_version=4)
              client = NotebookClient(nb, timeout=600, kernel_name="python3")
              client.execute(cwd=str(Path.cwd()))
          PY
      - name: Run starter notebooks
        run: |
          python - <<'PY'
          import nbformat
          from nbclient import NotebookClient
          from pathlib import Path

          notebooks = sorted(Path("days").glob("day*/notebook/*.ipynb"))
          if not notebooks:
              raise SystemExit("No starter notebooks found")

          for nb_path in notebooks:
              print(f"Executing {nb_path}")
              nb = nbformat.read(nb_path.open(), as_version=4)
              client = NotebookClient(nb, timeout=600, kernel_name="python3")
              client.execute(cwd=str(Path.cwd()))
          PY
